language: python
before_install:
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - bash Miniconda3-latest-Linux-x86_64.sh -b
    - . /home/travis/miniconda3/etc/profile.d/conda.sh
    - conda update --yes conda
    - conda config --add channels r
    - conda create --yes -n test
    - conda activate test
    - conda install --yes python=3.6
    - conda install --yes pycodestyle
    - conda install --yes pysimplegui

script:
    - python test_bioreflib.py
    - pycodestyle bioreflib.py
    - pycodestyle biorefine.py
    - pycodestyle GUI_biorefine.py
